Insert into testdashboard_pp (EVENT,EVENTSTATE,SEQNO) values ('CA Intraday Profile 1','45 times','1');
Insert into testdashboard_pp (EVENT,EVENTSTATE,SEQNO) values ('CA Intraday Profile 2','23 times','2');
Insert into testdashboard_pp (EVENT,EVENTSTATE,SEQNO) values ('CSC Intraday Profile','96 times','3');
Insert into testdashboard_pp (EVENT,EVENTSTATE,SEQNO) values ('CA Proceeds Paid Out','1296 Messages','4');
Insert into testdashboard_pp (EVENT,EVENTSTATE,SEQNO) values ('SBL AutoLend Processing','39643 Movements','5');
Insert into testdashboard_pp (EVENT,EVENTSTATE,SEQNO) values ('Intraday Customer Reports','3609 Messages','6');
Insert into testdashboard_pp (EVENT,EVENTSTATE,SEQNO) values ('BaNCS Businnes Date Flip','yesterday','7');
Insert into testdashboard_pp (EVENT,EVENTSTATE,SEQNO) values ('Archival of Historical Logs','two days ago','8');
Insert into testdashboard_pp (EVENT,EVENTSTATE,SEQNO) values ('Swift Customer Reports 940 (Messages)','4006','9');
Insert into testdashboard_pp (EVENT,EVENTSTATE,SEQNO) values ('Swift Customer Reports 950 (Messages)','194','10');
Insert into testdashboard_pp (EVENT,EVENTSTATE,SEQNO) values ('Swift Customer Reports 535 (Messages)','2499','11');
Insert into testdashboard_pp (EVENT,EVENTSTATE,SEQNO) values ('Swift Customer Reports 536 (Messages)','1230','12');
Insert into testdashboard_pp (EVENT,EVENTSTATE,SEQNO) values ('Swift Customer Reports 537 (Messages)','735','13');
Insert into testdashboard_pp (EVENT,EVENTSTATE,SEQNO) values ('Client Cash Movements (Transactions)','309570','14');
Insert into testdashboard_pp (EVENT,EVENTSTATE,SEQNO) values ('Client Cash Balance (Positions)','5142','15');
Insert into testdashboard_pp (EVENT,EVENTSTATE,SEQNO) values ('Client Security Position (Positions)','165443','16');
Insert into testdashboard_pp (EVENT,EVENTSTATE,SEQNO) values ('Client Security Movements (Transactions)','215048','17');
Insert into testdashboard_pp (EVENT,EVENTSTATE,SEQNO) values ('Internal Security Movements (Transactions)','77045','18');
Insert into testdashboard_pp (EVENT,EVENTSTATE,SEQNO) values ('Nostro Cash Movement (Transactions)','36963','19');
Insert into testdashboard_pp (EVENT,EVENTSTATE,SEQNO) values ('Nostro Cash Balance (Positions)','480','20');
Insert into testdashboard_pp (EVENT,EVENTSTATE,SEQNO) values ('Nostro Security Movement (Transactions)','38893','21');
Insert into testdashboard_pp (EVENT,EVENTSTATE,SEQNO) values ('Nostro Security Position (Positions)','53235','22');
Insert into testdashboard_pp (EVENT,EVENTSTATE,SEQNO) values ('Dataware House Extracts (Files)','69','23');
Insert into testdashboard_pp (EVENT,EVENTSTATE,SEQNO) values ('TreCM Extract (Transactions)','61276','24');
Insert into testdashboard_pp (EVENT,EVENTSTATE,SEQNO) values ('CA Instructions','88','25');
Insert into testdashboard_pp (EVENT,EVENTSTATE,SEQNO) values ('CA Depot Events','238','26');
Insert into testdashboard_pp (EVENT,EVENTSTATE,SEQNO) values ('CA Proceeds','533','27');
Insert into testdashboard_pp (EVENT,EVENTSTATE,SEQNO) values ('CA Client Payments Processed','994','28');
Insert into testdashboard_pp (EVENT,EVENTSTATE,SEQNO) values ('CA Announcements','1109','29');
Insert into testdashboard_pp (EVENT,EVENTSTATE,SEQNO) values ('CA MT566 generated','1761','30');
Insert into testdashboard_pp (EVENT,EVENTSTATE,SEQNO) values ('CA Notifications','5941','31');
Insert into testdashboard_pp (EVENT,EVENTSTATE,SEQNO) values ('MICS Netting Eligible Instructions','46089','32');
Insert into testdashboard_pp (EVENT,EVENTSTATE,SEQNO) values ('MICS OTC Instructions','11688','33');
Insert into testdashboard_pp (EVENT,EVENTSTATE,SEQNO) values ('Market Confirmations','34067','34');
Insert into testdashboard_pp (EVENT,EVENTSTATE,SEQNO) values ('Market Instructions','11484','35');
Insert into testdashboard_pp (EVENT,EVENTSTATE,SEQNO) values ('Market Status','40545','36');
Insert into testdashboard_pp (EVENT,EVENTSTATE,SEQNO) values ('NAM Confirmations','63490','37');
Insert into testdashboard_pp (EVENT,EVENTSTATE,SEQNO) values ('NAM Instructions','19523','38');
Insert into testdashboard_pp (EVENT,EVENTSTATE,SEQNO) values ('NAM Status','8','39');
Insert into testdashboard_pp (EVENT,EVENTSTATE,SEQNO) values ('SEPA Messages','14','40');
Insert into testdashboard_pp (EVENT,EVENTSTATE,SEQNO) values ('SWIFT 101 Messages','41','41');
Insert into testdashboard_pp (EVENT,EVENTSTATE,SEQNO) values ('SWIFT 103 Messages','67','42');
Insert into testdashboard_pp (EVENT,EVENTSTATE,SEQNO) values ('SWIFT 202 Messages','405','43');
Insert into testdashboard_pp (EVENT,EVENTSTATE,SEQNO) values ('SWIFT 910 Messages','283','44');
Insert into testdashboard_pp (EVENT,EVENTSTATE,SEQNO) values ('MICS Clearing Message Based','1755','45');
Insert into testdashboard_pp (EVENT,EVENTSTATE,SEQNO) values ('MICS Clearing File Based','11578','46');
Insert into testdashboard_pp (EVENT,EVENTSTATE,SEQNO) values ('Security Positions (Including vostro,nostro and suspense )','935092','47');
Insert into testdashboard_pp (EVENT,EVENTSTATE,SEQNO) values ('Cash Positions (Including vostro,nostro and suspense Across currencies)','57248','48');
Insert into testdashboard_pp (EVENT,EVENTSTATE,SEQNO) values ('Financial Instruments / products (Active) (Including Equities, Bonds, warrants, Funds, Miscellaneous)','259172','49');
Insert into testdashboard_pp (EVENT,EVENTSTATE,SEQNO) values ('Security Accounts managed (Including vostro, nostro and suspense accounts)','2010','50');
Insert into testdashboard_pp (EVENT,EVENTSTATE,SEQNO) values ('Cash Accounts managed (Including vostro, nostro and suspense accounts)','57290','51');
