Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Trade Processing','CSD Specific requirements',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Trade Processing','Processing of all 22F:SETR Tags',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Trade Processing','MT548 when Trade id in TBR status',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Trade Processing','RDO Creation  -  Manual Creation',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Trade Processing','RDO Creation  -  STP creation',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Trade Processing','RDO Repair  -  Manual Repair',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Trade Processing','RDO Repair  -  Batch Repair',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Trade Processing','RDO Matching  -  Manual Matching',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Trade Processing','RDO Matching  -  STP /MT 548 Matching',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Trade Processing','RDO Settlement   -  STP Settlement',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Trade Processing','RDO Settlement   -  Manual Settlement',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Trade Processing','RDO Settlement   -  Settlement Reprocessing batch',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Trade Processing','RDO Cancellation  -  Manual Cancellation',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Trade Processing','RDO Cancellation  -  MT54X Client Cancellation',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Trade Processing','RDO Cancellation  -  MT548 Market Cancellation',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Trade Processing','Internal Trades  -  Manual Creation',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Trade Processing','Internal Trades  -  STP  Creation',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Trade Processing','Internal Trades  -  STP matching',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Trade Processing','Internal Trades  -  Batch matching',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Trade Processing','Internal Trades  -  Auto Settlement batch',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Trade Processing','Internal External Trades  -  Manual Creation',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Trade Processing','Internal External Trades  -  STP  Creation',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Trade Processing','Internal External Trades  -  STP matching',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Trade Processing','Internal External Trades  -  Batch matching',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Trade Processing','Internal External Trades  -  Auto Settlement batch',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Trade Processing','Internal Internal Trades  -  Manual Creation',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Trade Processing','Internal Internal Trades  -  STP Creation',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Trade Processing','Internal Internal Trades  -  STP matching',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Trade Processing','Internal Internal Trades  -  Batch matching',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Trade Processing','Internal Internal Trades  -  Auto Settlement batch',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Trade Processing','XBANCS Trades  -  XBANCS trades creation and Matching ',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Trade Processing','XBANCS Trades  -  XBANCS trade Auto settlement batch',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Trade Processing','Dump Trades    ',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Trade Processing','Turn Trades    ',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Trade Processing','Netted Trades    ',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Trade Processing','Netting Eligible Trades    ',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Trade Processing','Loan/Borrow trades  -  Loan Transaction ',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Trade Processing','Loan/Borrow trades  -  Loan Repay',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Trade Processing','Loan/Borrow trades  -  Borrow Transaction',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Trade Processing','Loan/Borrow trades  -  Borrow Repay',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Trade Processing','Loan/Borrow trades  -  Loan Transaction Confirmation',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Trade Processing','Loan/Borrow trades  -  Loan Repay Confirmation',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Trade Processing','Loan/Borrow trades  -  Borrow Transaction Confirmation',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Trade Processing','Loan/Borrow trades  -  Borrow Repay Confirmation',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Trade Processing','Hold Market trades(PREA)  -  Settlement Deliver',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Broker Allegement','Broker Allegement  -  Manual creation',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Broker Allegement','Broker Allegement  -  MT578 STP creation',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Broker Allegement','Broker Allegement  -  STP Matching',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Broker Allegement','Broker Allegement  -  Manual Matching',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Broker Allegement','Broker Allegement  -  Matching through batch 95004',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Broker Allegement','Broker Allegement  -  Near Matching through batch',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('CA Transformation','Inject MT54X Messages',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('CA Transformation','Batch Execution',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('BRN','Batch execution BOD',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('BRN','Batch execution EOD',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('BRN','Verification',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('BRN','BRN trades  -  Receive BRN trades',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('BRN','BRN trades  -  Deliver BRN Trades',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('BRN','BRN trades  -  BRN trades Nostro transfer cancellation/creation batch',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('BRN','BRN trades  -  BRN RVP trade release batch',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Valuation&position check','Instruction injection DVP/DFP/DWP for custody check',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Valuation&position check','Batch 5013 verification',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Valuation&position check','Batch 5017  & 5042 verification',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Valuation&position check','Cash Position Check Valuation-Instruction Injection(RVP/DWP/PMO)',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Valuation&position check','Batch execution ',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Valuation&position check','Verification',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Statement Msg','MT535 Verification',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Statement Msg','MT536 Verification',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Statement Msg','MT537 Verification',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Statement Msg','MT940 Verification',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Statement Msg','MT950 Verfication',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('DWH Reports','Dataware Housing RefData Extracts',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('DWH Reports','Dataware Housing Txn Data Extracts',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('DWH Reports','Dataware Housing Static Configuration Extracts',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Synchronization','MT54X Synchronization towards MICS',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Synchronization','Confirmation Synchronization',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Synchronization','Status message synchronization',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Synchronization','CASH SYNC out to mics',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Synchronization','Sec sync out to Mics',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Data Management','Table Difference All (txn data )',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Data Management','Manual entries',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Data Management','Manual Modification',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Payments','Inbound Payment Processing MT103',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Payments','Inbound Payment Confirmation MT910',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Payments','Inbound Payment Processing MT202',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Payments','Inbound Payment Processing  PACS.008',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Payments','Outbound Payment Processing MT101',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Payments','Outbound Payment Processing MT103',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Payments','Outbound Payment Processing MT202',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Payments','Outbound Payment Processing PAIN.001',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Payments','Internal Transfer Processing  MT103',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Payments','Internal Transfer Processing  MT202',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Payments','Internal Transfer Processing  PAIN.001',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Payments','Internal Transfer Nostro Side Processing - TreCM Flow',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Payments','FX Order Manual Flow ',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Payments','FX Order Execution & Netted FX Order Creation Batch ',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Payments','FX Deal  Creation and Execution Batch ',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Payments','Sweep Order Cash Balanace based creation & execution batch',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('Payments','Sweep Order Transaction Date based creation & execution batch',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('SBL Specifics','Auto borrow Processing',null);
Insert into testdashboard_bluecard (FUNCTIONAREAS,COVEREDSCENARIOS,SEQNO) values ('SBL Specifics','Auto Lend Processing',null);
