Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('235','Log-Error-6079-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('236','Log-Debug-6079-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('237','Log-Error-6080-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('238','Log-Debug-6080-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('239','Log-Debug-90102-GPC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('240','Log-Error-95015-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('241','Log-Error-8051-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('242','Log-Debug-8051-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('243','Log-Debug-8052-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('244','Log-Error-8052-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('245','Log-Error-90102-GPC.log.1','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('246','Log-Error-90102-GPC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('247','Log-Debug-8053-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('248','Log-Error-8053-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('249','Log-Debug-8054-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('250','Log-Error-8054-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('251','Log-Error-8058-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('252','Log-Debug-8058-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('253','Log-Error-6084-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('254','Log-Debug-6084-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('255','Log-Error-8066-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('256','Log-Debug-8066-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('257','Log-Error-8067-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('258','Log-Debug-8067-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('259','Log-Error-8090-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('260','Log-Debug-8090-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('261','Log-Error-8094-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('262','Log-Debug-8094-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('263','Log-Error-8095-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('264','Log-Debug-8095-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('265','Log-Error-8096-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('266','Log-Debug-8096-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('267','Log-Error-8097-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('268','Log-Debug-8097-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('269','Log-Error-8101-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('270','Log-Debug-8101-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('271','Log-Error-8102-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('272','Log-Debug-8102-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('273','Log-Debug-6074-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('274','Log-Error-6074-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('275','Log-Debug-8056-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('276','Log-Error-8056-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('277','Log-Error-8057-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('278','Log-Debug-8057-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('279','Log-Error-8059-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('280','Log-Debug-8059-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('281','Log-Debug-8088-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('282','Log-Error-8088-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('283','Log-Debug-8080-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('284','Log-Error-8080-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('285','Log-Error-8084-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('286','Log-Debug-8084-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('287','Log-Debug-8085-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('288','Log-Error-8085-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('289','Log-Debug-8086-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('290','Log-Error-8086-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('291','Log-Error-8087-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('292','Log-Debug-8087-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('293','Log-Debug-8089-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('294','Log-Error-8089-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('295','Log-Debug-8091-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('296','Log-Error-8091-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('297','Log-Debug-8092-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('298','Log-Error-8092-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('299','Log-Error-1040-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('300','Log-Debug-1040-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('301','Log-Error-90000-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('302','Log-Debug-90000-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('303','Log-Error-1041-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('304','Log-Debug-1041-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('305','Log-Debug-154-GPC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('306','Log-Debug-154-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('307','Log-Error-154-GPC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('308','Log-Error-154-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('309','Log-Error-155-GPC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('310','Log-Error-155-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('311','Log-Debug-155-GPC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('312','Log-Debug-155-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('313','Log-Error-9990-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('314','Log-Debug-9990-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('315','Log-Error-90105-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('316','Log-Debug-90105-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('317','Log-Error-156-GPC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('318','Log-Debug-156-GPC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('319','Log-Error-1301-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('320','Log-Debug-1301-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('321','Log-Error-95012-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('322','Log-Debug-95012-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('323','Log-Debug-90022-GPC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('324','Log-Error-90022-GPC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('325','Log-Error-90021-GPC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('326','Log-Debug-90021-GPC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('327','Log-Error-90033-GPC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('328','Log-Debug-90033-GPC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('329','Log-Debug-91015-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('330','Log-Error-95021-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('331','Log-Debug-95021-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('332','Log-Error-9000-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('333','Log-Debug-9000-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('334','Log-Error-9009-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('335','Log-Debug-9009-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('336','Log-Error-9999-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('337','Log-Debug-9999-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('338','Log-Error-91011-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('339','Log-Debug-91011-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('340','Log-Debug-90034-GPC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('341','Log-Error-90034-GPC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('342','Log-Error-5002-GPC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('343','Log-Debug-5002-GPC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('344','Log-Debug-91013-GPC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('345','Log-Error-91013-GPC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('346','Log-Error-91015-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('347','Log-Debug-44-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('348','Log-Error-44-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('349','Log-Debug-950-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('350','Log-Error-950-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('351','Log-Error-94009-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('352','Log-Debug-94009-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('353','Log-Debug-940-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('354','Log-Error-940-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('355','Log-Error-6632-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('356','Log-Debug-6632-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('357','Log-Error-6644-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('358','Log-Error-6641-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('359','Log-Debug-6644-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('360','Log-Debug-6641-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('361','Log-Error-6630-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('362','Log-Debug-6630-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('363','Log-Error-6631-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('364','Log-Debug-6631-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('365','Log-Error-6640-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('366','Log-Error-6634-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('367','Log-Debug-6640-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('368','Log-Debug-6634-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('369','Log-Error-6633-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('370','Log-Debug-6633-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('371','Log-Error-6643-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('372','Log-Error-6642-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('373','Log-Debug-6643-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('374','Log-Debug-6642-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('375','Log-Debug-5012-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('376','Log-Error-5012-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('377','Log-Error-7733-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('378','Log-Debug-7733-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('379','Log-Debug-773-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('380','Log-Error-7732-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('381','Log-Debug-7732-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('382','Log-Error-774-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('383','Log-Error-7741-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('384','Log-Debug-774-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('385','Log-Debug-7741-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('386','Log-Error-7731-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('387','Log-Debug-7731-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('388','Log-Debug-5137-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('389','Log-Error-5137-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('390','Log-Debug-5079-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('391','Log-Error-7744-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('392','Log-Error-5079-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('393','Log-Debug-7744-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('394','Log-Error-7743-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('395','Log-Error-7734-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('396','Log-Debug-7743-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('397','Log-Debug-7734-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('398','Log-Debug-5136-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('399','Log-Error-7742-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('400','Log-Error-5136-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('2',' BancsOnline-Fatal.log','/opt/jboss/ncshome/AAC/Batch/logs/','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('3',' BancsOnline-Error.log','/opt/jboss/ncshome/AAC/Batch/logs/','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('4',' BancsOnline-Debug.log','/opt/jboss/ncshome/AAC/Batch/logs/','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('5',' BancsBatch-Info.log','/opt/jboss/ncshome/AAC/Batch/logs/','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('6',' com.tcs.ncs.eic.CreateEventDetails','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('7',' com.tcs.ncs.eic.CreateEventDetails','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('8',' com.tcs.ncs.eic.CreateEventDetails','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('9',' com.tcs.ncs.eic.CreateEventDetails','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('10',' com.tcs.ncs.emc.DepotEventCreation','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('11',' com.tcs.ncs.emc.DepotEventCreation','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('12',' com.tcs.ncs.emc.DepotEventCreation','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('13',' com.tcs.ncs.emc.DepotEventCreation','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('14',' com.tcs.ncs.emc.RequestGeneration','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('15',' com.tcs.ncs.emc.RequestGeneration','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('16',' com.tcs.ncs.emc.RequestGeneration','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('17',' com.tcs.ncs.emc.RequestGeneration','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('18',' com.tcs.ncs.emc.PositionResponseCS','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('19',' com.tcs.ncs.emc.PositionResponseCS','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('20',' com.tcs.ncs.emc.PositionResponseCS','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('21',' com.tcs.ncs.emc.PositionResponseCS','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('22',' com.tcs.ncs.emc.SpecialProcessingF','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('23',' com.tcs.ncs.emc.SpecialProcessingF','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('24',' com.tcs.ncs.emc.SpecialProcessingF','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('25',' com.tcs.ncs.emc.SpecialProcessingF','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('26',' com.tcs.ncs.emc.PositionRefresh','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('27',' com.tcs.ncs.emc.PositionRefresh','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('28',' com.tcs.ncs.emc.PositionRefresh','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('29',' com.tcs.ncs.emc.PositionRefresh','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('30',' com.tcs.ncs.emc.TransactionElgComp','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('31',' com.tcs.ncs.emc.TransactionElgComp','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('32',' com.tcs.ncs.emc.TransactionElgComp','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('33',' com.tcs.ncs.emc.TransactionElgComp','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('34',' com.tcs.ncs.emc.EligibilityCorrect','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('35',' com.tcs.ncs.emc.EligibilityCorrect','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('36',' com.tcs.ncs.emc.EligibilityCorrect','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('37',' com.tcs.ncs.emc.EligibilityCorrect','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('38',' com.tcs.ncs.emc.BalancingEntitleme','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('39',' com.tcs.ncs.emc.BalancingEntitleme','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('40',' com.tcs.ncs.emc.BalancingEntitleme','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('41',' com.tcs.ncs.emc.BalancingEntitleme','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('42',' com.tcs.ncs.fmc.FeeComputationOnEn','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('43',' com.tcs.ncs.fmc.FeeComputationOnEn','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('44',' com.tcs.ncs.fmc.FeeComputationOnEn','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('45',' com.tcs.ncs.fmc.FeeComputationOnEn','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('46',' com.tcs.ncs.tmc.RecomputeTransacti','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('47',' com.tcs.ncs.tmc.RecomputeTransacti','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('48',' com.tcs.ncs.tmc.RecomputeTransacti','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('49',' com.tcs.ncs.tmc.RecomputeTransacti','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('50',' com.tcs.ncs.nmc.GenerateGoldenAnnc','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('51',' com.tcs.ncs.nmc.GenerateGoldenAnnc','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('52',' com.tcs.ncs.nmc.GenerateGoldenAnnc','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('53',' com.tcs.ncs.nmc.GenerateGoldenAnnc','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('54',' com.tcs.ncs.nmc.GeneratePreAnnounc','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('55',' com.tcs.ncs.nmc.GeneratePreAnnounc','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('56',' com.tcs.ncs.nmc.GeneratePreAnnounc','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('57',' com.tcs.ncs.nmc.GeneratePreAnnounc','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('58',' com.tcs.ncs.nmc.GenerateOutgoingMT','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('59',' com.tcs.ncs.nmc.GenerateOutgoingMT','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('60',' com.tcs.ncs.nmc.GenerateOutgoingMT','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('61',' com.tcs.ncs.nmc.GenerateOutgoingMT','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('62',' com.tcs.ncs.nmc.UpdatedAnnouncemen','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('63',' com.tcs.ncs.nmc.UpdatedAnnouncemen','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('64',' com.tcs.ncs.nmc.UpdatedAnnouncemen','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('65',' com.tcs.ncs.nmc.UpdatedAnnouncemen','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('66',' com.tcs.ncs.nmc.ChangeInClntPos','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('67',' com.tcs.ncs.nmc.ChangeInClntPos','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('68',' com.tcs.ncs.nmc.ChangeInClntPos','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('69',' com.tcs.ncs.nmc.ChangeInClntPos','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('70',' com.tcs.ncs.nmc.GenerateOutgoingMT','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('71',' com.tcs.ncs.nmc.GenerateOutgoingMT','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('72',' com.tcs.ncs.nmc.GenerateOutgoingMT','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('73',' com.tcs.ncs.nmc.GenerateOutgoingMT','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('74',' com.tcs.ncs.tmc.RecomputeEventStat','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('75',' com.tcs.ncs.tmc.RecomputeEventStat','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('76',' com.tcs.ncs.tmc.RecomputeEventStat','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('77',' com.tcs.ncs.tmc.RecomputeEventStat','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('78',' com.tcs.ncs.nmc.GenerateOutgoingMT','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('79',' com.tcs.ncs.nmc.GenerateOutgoingMT','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('80',' com.tcs.ncs.nmc.GenerateOutgoingMT','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('81',' com.tcs.ncs.nmc.GenerateOutgoingMT','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('82',' com.tcs.ncs.nmc.UpdateNotfOtgngMsg','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('83',' com.tcs.ncs.nmc.UpdateNotfOtgngMsg','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('84',' com.tcs.ncs.nmc.UpdateNotfOtgngMsg','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('85',' com.tcs.ncs.nmc.UpdateNotfOtgngMsg','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('86',' 08-Aug-2016','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('87',' com.tcs.ncs.cmc.RecomputeClaims','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('88',' com.tcs.ncs.cmc.RecomputeClaims','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('89',' com.tcs.ncs.cmc.RecomputeClaims','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('90',' com.tcs.ncs.cmc.RecomputeClaims','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('91',' 09-Aug-2016','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('92',' com.tcs.ncs.emc.TradeResponseCSP','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('93',' com.tcs.ncs.emc.TradeResponseCSP','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('94',' com.tcs.ncs.emc.TradeResponseCSP','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('95',' com.tcs.ncs.emc.TradeResponseCSP','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('96',' 10-Aug-2016','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('97',' 11-Aug-2016','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('98',' 12-Aug-2016','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('99',' com.tcs.ncs.rcc.ProcessDfltOptnRes','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('100',' com.tcs.ncs.rcc.ProcessDfltOptnRes','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('101',' com.tcs.ncs.rcc.ProcessDfltOptnRes','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('102',' com.tcs.ncs.rcc.ProcessDfltOptnRes','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('103',' 15-Aug-2016','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('104',' 16-Aug-2016','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('105',' 17-Aug-2016','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('106',' com.tcs.ncs.anc.AlrtOnAnncmnt','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('107',' com.tcs.ncs.anc.AlrtOnAnncmnt','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('108',' com.tcs.ncs.anc.AlrtOnAnncmnt','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('109',' com.tcs.ncs.anc.AlrtOnAnncmnt','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('110',' com.tcs.ncs.anc.DuplicateAnnPblshn','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('111',' com.tcs.ncs.anc.DuplicateAnnPblshn','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('112',' com.tcs.ncs.anc.DuplicateAnnPblshn','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('113',' com.tcs.ncs.anc.DuplicateAnnPblshn','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('114',' 18-Aug-2016','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('115',' com.tcs.ncs.chn.GenerateChannelRes','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('116',' com.tcs.ncs.chn.GenerateChannelRes','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('117',' com.tcs.ncs.chn.GenerateChannelRes','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('118',' com.tcs.ncs.chn.GenerateChannelRes','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('119',' 19-Aug-2016','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('120',' com.tcs.ncs.rcc.ApplyProrationBatc','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('121',' com.tcs.ncs.rcc.ApplyProrationBatc','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('122',' com.tcs.ncs.rcc.ApplyProrationBatc','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('123',' com.tcs.ncs.rcc.ApplyProrationBatc','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('124',' com.tcs.ncs.emc.PositionEnttComput','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('125',' com.tcs.ncs.emc.PositionEnttComput','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('126',' com.tcs.ncs.emc.PositionEnttComput','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('127',' com.tcs.ncs.emc.PositionEnttComput','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('128',' com.tcs.ncs.emc.TransEnttComputati','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('129',' com.tcs.ncs.emc.TransEnttComputati','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('130',' com.tcs.ncs.emc.TransEnttComputati','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('131',' com.tcs.ncs.emc.TransEnttComputati','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('132',' 22-Aug-2016','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('133',' com.tcs.ncs.anc.CriticalDtWrklist','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('134',' com.tcs.ncs.anc.CriticalDtWrklist','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('135',' com.tcs.ncs.anc.CriticalDtWrklist','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('136',' com.tcs.ncs.anc.CriticalDtWrklist','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('137',' com.tcs.ncs.eic.ProcessPotentialLi','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('138',' com.tcs.ncs.eic.ProcessPotentialLi','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('139',' com.tcs.ncs.eic.ProcessPotentialLi','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('140',' com.tcs.ncs.eic.ProcessPotentialLi','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('141',' com.tcs.ncs.cmc.LateTradeClaim','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('142',' com.tcs.ncs.cmc.LateTradeClaim','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('143',' com.tcs.ncs.cmc.LateTradeClaim','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('144',' com.tcs.ncs.cmc.LateTradeClaim','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('145',' com.tcs.ncs.tmc.RecmputeTrnsctnAtE','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('146',' com.tcs.ncs.tmc.RecmputeTrnsctnAtE','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('147',' com.tcs.ncs.tmc.RecmputeTrnsctnAtE','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('148',' com.tcs.ncs.tmc.RecmputeTrnsctnAtE','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('149',' com.tcs.ncs.anc.ChkPrcdRule','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('150',' com.tcs.ncs.anc.ChkPrcdRule','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('151',' com.tcs.ncs.anc.ChkPrcdRule','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('152',' com.tcs.ncs.anc.ChkPrcdRule','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('153','Log-Debug-95113-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('154','Log-Debug-53000-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('155','Log-Debug-95014-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('156','Log-Debug-95015-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('157','Log-Debug-95114-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('158','Log-Error-6094-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('159','Log-Debug-6094-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('160','Log-Debug-8076-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('161','Log-Error-8076-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('162','Log-Error-8077-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('163','Log-Debug-8077-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('164','Log-Debug-8100-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('165','Log-Error-8100-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('166','Log-Debug-8305-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('167','Log-Error-8104-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('168','Log-Debug-8104-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('169','Log-Debug-8105-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('170','Log-Error-8105-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('171','Log-Error-8106-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('172','Log-Debug-8106-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('173','Log-Error-8107-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('174','Log-Debug-8107-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('175','Log-Error-6033-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('176','Log-Debug-6033-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('177','Log-Debug-8111-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('178','Log-Error-8111-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('179','Log-Error-8112-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('180','Log-Debug-8112-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('181','Log-Error-6040-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('182','Log-Debug-6040-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('183','Log-Error-6081-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('184','Log-Debug-6081-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('185','Log-Error-6082-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('186','Log-Debug-6082-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('187','Log-Error-6083-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('188','Log-Debug-6083-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('189','Log-Error-6085-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('190','Log-Debug-6085-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('191','Log-Error-6086-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('192','Log-Debug-6086-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('193','Log-Error-6087-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('194','Log-Debug-6087-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('195','Log-Error-6088-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('196','Log-Debug-6088-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('197','Log-Error-6089-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('198','Log-Debug-6089-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('199','Log-Error-6090-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('200','Log-Debug-6090-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('201','Log-Error-8061-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('202','Log-Debug-8061-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('203','Log-Error-8062-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('204','Log-Debug-8062-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('205','Log-Error-8063-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('206','Log-Debug-8063-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('207','Log-Error-8064-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('208','Log-Debug-8064-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('209','Log-Error-8068-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('210','Log-Debug-8068-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('211','Log-Error-8069-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('212','Log-Debug-8069-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('213','Log-Error-8098-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('214','Log-Debug-8098-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('215','Log-Error-8099-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('216','Log-Debug-8099-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('217','Log-Error-6023-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('218','Log-Debug-6023-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('219','Log-Error-6030-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('220','Log-Debug-6030-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('221','Log-Error-6071-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('222','Log-Debug-6071-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('223','Log-Error-6072-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('224','Log-Debug-6072-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('225','Log-Error-6073-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('226','Log-Debug-6073-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('227','Log-Debug-6075-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('228','Log-Error-6075-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('229','Log-Error-6076-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('230','Log-Debug-6076-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('231','Log-Debug-6077-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('232','Log-Error-6077-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('233','Log-Error-6078-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('234','Log-Debug-6078-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('401','Log-Debug-7742-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('402','Log-Debug-5078-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('403','Log-Error-5078-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('404','Log-Debug-5080-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('405','Log-Error-5080-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('406','Log-Error-773-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('407','Log-Debug-5135-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('408','Log-Error-5135-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('409','Log-Debug-95010-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('410','Log-Error-95010-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('411','Log-Error-95-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('412','Log-Debug-95-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('413','Log-Error-24-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('414','Log-Debug-24-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('415','Log-Error-8999-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('416','Log-Debug-8999-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('417','Log-Debug-153-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('418','Log-Error-153-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('419','Log-Debug-152-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('420','Log-Error-152-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('421','Log-Debug-8050-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('422','Log-Error-8007-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('423','Log-Error-5020-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('424','Log-Debug-8007-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('425','Log-Debug-5020-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('426','Log-Error-76-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('427','Log-Debug-76-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('428','Log-Error-8050-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('429','Log-Error-50017-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('430','Log-Debug-50017-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('431','Log-Error-90032-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('432','Log-Debug-90032-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('433','Log-Debug-7737-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('434','Log-Error-7737-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('435','Log-Debug-7738-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('436','Log-Error-7738-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('437','Log-Debug-90146-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('438','Log-Error-90146-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('439','Log-Debug-90147-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('440','Log-Error-90147-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('441','Log-Debug-95003-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('442','Log-Error-95003-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('443','Log-Error-90027-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('444','Log-Debug-90027-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('445','Log-Debug-7739-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('446','Log-Error-7739-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('447','Log-Debug-90041-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('448','Log-Error-90041-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('449','Log-Error-7740-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('450','Log-Debug-7740-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('451','Log-Debug-91012-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('452','Log-Error-95034-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('453','Log-Debug-95034-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('454','Log-Debug-95032-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('455','Log-Debug-50200-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('456','Log-Debug-50300-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('457','Log-Error-95032-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('458','Log-Debug-95033-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('459','Log-Error-95033-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('460','Log-Debug-50400-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('461','Log-Debug-5024-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('462','Log-Error-5024-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('463','Log-Error-52011-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('464','Log-Debug-52011-AAC.log','/opt/jboss/ncshome/AAC/Batch/logs/LogFiles','10.248.1.76');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('465','messageEAIlog','/opt/jboss/SI_HOME_7.1.10/LOGS','10.248.1.77');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('466','messageBaNCSSIlog','/opt/jboss/SI_HOME_7.1.10/LOGS','10.248.1.77');
Insert into testdashboard_al (SEQNO,PROGRAMNAME,PATH,HOSTNAME) values ('467','messageSILoglog','/opt/jboss/SI_HOME_7.1.10/LOGS','10.248.1.77');